# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/


variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - apt-get -y update
    - apt-get -y install g++
    - apt-get -y install libasio-dev
    - apt-get -y install libboost-system-dev
    - apt-get -y install cmake
    - apt-get -y install libc++-dev

# run tests using the binary built before
test:
  image: debian:latest
  stage: test
  script:
    - cd ./tests
    - cmake .
    - make
    - ./stream_pipe_test
    - ./ring_buffer_test
    - ./http_parser_test
    - ./http_inbound_connection_test
